version: '3'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    labels:
      NAME: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${_rabbitMqUser}
      - RABBITMQ_DEFAULT_PASS=${_rabbitMqPassword}
    ports:
      - "15801:15672"
      - "5674:5672"
    expose:
      - 5672
      - 15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - coworkhubnet

  coworkhub-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${_saPassword}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    expose:
      - 1433
    networks:
      - coworkhubnet
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P CoWorkHub2026! -Q 'SELECT 1'"]
      interval: 10s
      retries: 10
      timeout: 5s   

  coworkhub-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings__CoWorkHubConnection=Server=coworkhub-sql,1433;Database=210095;User=sa;Password=${_saPassword};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - _fromAddress=${_fromAddress}
      - _password=${_password}
      - _host=${_host}
      - _enableSSL=${_enableSSL}
      - _displayName=${_displayName}
      - _timeout=${_timeout}
      - _port=${_port}
      - _rabbitMqHost=rabbitmq
      - _rabbitMqUser=${_rabbitMqUser}
      - _rabbitMqPassword=${_rabbitMqPassword}
      - _rabbitMqPort=${_rabbitMqPort}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_SECRET=${PAYPAL_SECRET}
      - PAYPAL_MODE=${PAYPAL_MODE}
      - PAYPAL_CURRENCY=${PAYPAL_CURRENCY}
      - PAYPAL_SUCCESS_URL=${PAYPAL_SUCCESS_URL}
      - PAYPAL_CANCEL_URL=${PAYPAL_CANCEL_URL}
      - _saPassword=${_saPassword}
    ports:
      - "5084:5084"
    networks:
      - coworkhubnet
    links:
      - coworkhub-sql
    depends_on:
      - coworkhub-sql
      - rabbitmq

  coworkhub-console:
    restart: on-failure
    build:
      context: .
      dockerfile: CoWorkHub.Subscriber/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    environment:
      - _fromAddress=${_fromAddress}
      - _password=${_password}
      - _host=${_host}
      - _enableSSL=${_enableSSL}
      - _displayName=${_displayName}
      - _timeout=${_timeout}
      - _port=${_port}
      - _rabbitMqHost=${_rabbitMqHost}
      - _rabbitMqUser=${_rabbitMqUser}
      - _rabbitMqPassword=${_rabbitMqPassword}
      - _rabbitMqPort=${_rabbitMqPort}
    networks:
      - coworkhubnet

  coworkhub-worker:
    image: coworkhub-coworkhub-worker
    container_name: worker
    restart: no
    build:
      context: .
      dockerfile: CoWorkHub.Worker/Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionStrings__CoWorkHubConnection=Server=coworkhub-sql,1433;Database=210095;User=sa;Password=${_saPassword};Trusted_Connection=False;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - coworkhub-sql
      - coworkhub-api
    networks:
      - coworkhubnet

networks:
  coworkhubnet:
    driver: bridge